
  export const itemsTest= [
        {
          id: '1',
          name: 'Producto 1',
          msrp: 50,
          price: 40,
          sku: 'SKU001',
          description: 'Descripción del Producto 1',
          status: 'AVAILABLE',
          media: ['imagen1.jpg', 'imagen2.jpg'],
          item_weight_net: 1.5,
          item_weight_gross: 2.0,
          item_size_width: 10,
          item_size_depth: 5,
          item_size_height: 15,
          package_weight_net: 2.5,
          package_weight_gross: 3.0,
          package_size_width: 12,
          package_size_depth: 7,
          package_size_height: 17,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory1',
          factory: {
            id: 'factory1',
            name: 'Fábrica 1',
            url: 'https://fabrica1.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 1',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '2',
          name: 'Producto 2',
          msrp: 60,
          price: 45,
          sku: 'SKU002',
          description: 'Descripción del Producto 2',
          status: 'AVAILABLE',
          media: ['imagen3.jpg', 'imagen4.jpg'],
          item_weight_net: 2.0,
          item_weight_gross: 2.5,
          item_size_width: 12,
          item_size_depth: 6,
          item_size_height: 17,
          package_weight_net: 3.0,
          package_weight_gross: 3.5,
          package_size_width: 14,
          package_size_depth: 8,
          package_size_height: 19,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory2',
          factory: {
            id: 'factory2',
            name: 'Fábrica 2',
            url: 'https://fabrica2.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 2',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '3',
          name: 'Producto 3',
          msrp: 53,
          price: 43,
          sku: 'SKU003',
          description: 'Descripción del Producto 3',
          status: 'AVAILABLE',
          media: ['imagen5.jpg', 'imagen6.jpg'],
          item_weight_net: 1.8,
          item_weight_gross: 2.3,
          item_size_width: 13,
          item_size_depth: 8,
          item_size_height: 18,
          package_weight_net: 2.8,
          package_weight_gross: 3.3,
          package_size_width: 15,
          package_size_depth: 9,
          package_size_height: 20,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory3',
          factory: {
            id: 'factory3',
            name: 'Fábrica 3',
            url: 'https://fabrica3.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 3',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '4',
          name: 'Producto 4',
          msrp: 54,
          price: 44,
          sku: 'SKU004',
          description: 'Descripción del Producto 4',
          status: 'AVAILABLE',
          media: ['imagen7.jpg', 'imagen8.jpg'],
          item_weight_net: 1.9,
          item_weight_gross: 2.4,
          item_size_width: 14,
          item_size_depth: 9,
          item_size_height: 19,
          package_weight_net: 2.9,
          package_weight_gross: 3.4,
          package_size_width: 16,
          package_size_depth: 10,
          package_size_height: 21,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory4',
          factory: {
            id: 'factory4',
            name: 'Fábrica 4',
            url: 'https://fabrica4.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 4',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '5',
          name: 'Producto 5',
          msrp: 55,
          price: 45,
          sku: 'SKU005',
          description: 'Descripción del Producto 5',
          status: 'AVAILABLE',
          media: ['imagen9.jpg', 'imagen10.jpg'],
          item_weight_net: 2.0,
          item_weight_gross: 2.5,
          item_size_width: 15,
          item_size_depth: 10,
          item_size_height: 20,
          package_weight_net: 3.0,
          package_weight_gross: 3.5,
          package_size_width: 17,
          package_size_depth: 11,
          package_size_height: 22,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory5',
          factory: {
            id: 'factory5',
            name: 'Fábrica 5',
            url: 'https://fabrica5.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 5',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '6',
          name: 'Producto 6',
          msrp: 56,
          price: 46,
          sku: 'SKU006',
          description: 'Descripción del Producto 6',
          status: 'AVAILABLE',
          media: ['imagen11.jpg', 'imagen12.jpg'],
          item_weight_net: 2.1,
          item_weight_gross: 2.6,
          item_size_width: 16,
          item_size_depth: 11,
          item_size_height: 21,
          package_weight_net: 3.1,
          package_weight_gross: 3.6,
          package_size_width: 18,
          package_size_depth: 12,
          package_size_height: 23,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory6',
          factory: {
            id: 'factory6',
            name: 'Fábrica 6',
            url: 'https://fabrica6.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 6',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '7',
          name: 'Producto 7',
          msrp: 57,
          price: 47,
          sku: 'SKU007',
          description: 'Descripción del Producto 7',
          status: 'AVAILABLE',
          media: ['imagen13.jpg', 'imagen14.jpg'],
          item_weight_net: 2.2,
          item_weight_gross: 2.7,
          item_size_width: 17,
          item_size_depth: 12,
          item_size_height: 22,
          package_weight_net: 3.2,
          package_weight_gross: 3.7,
          package_size_width: 19,
          package_size_depth: 13,
          package_size_height: 24,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory7',
          factory: {
            id: 'factory7',
            name: 'Fábrica 7',
            url: 'https://fabrica7.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 7',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },{
          id: '8',
          name: 'Producto 8',
          msrp: 58,
          price: 48,
          sku: 'SKU008',
          description: 'Descripción del Producto 8',
          status: 'AVAILABLE',
          media: ['imagen15.jpg', 'imagen16.jpg'],
          item_weight_net: 2.3,
          item_weight_gross: 2.8,
          item_size_width: 18,
          item_size_depth: 13,
          item_size_height: 23,
          package_weight_net: 3.3,
          package_weight_gross: 3.8,
          package_size_width: 20,
          package_size_depth: 14,
          package_size_height: 25,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory8',
          factory: {
            id: 'factory8',
            name: 'Fábrica 8',
            url: 'https://fabrica8.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 8',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '9',
          name: 'Producto 9',
          msrp: 59,
          price: 49,
          sku: 'SKU009',
          description: 'Descripción del Producto 9',
          status: 'AVAILABLE',
          media: ['imagen17.jpg', 'imagen18.jpg'],
          item_weight_net: 2.4,
          item_weight_gross: 2.9,
          item_size_width: 19,
          item_size_depth: 14,
          item_size_height: 24,
          package_weight_net: 3.4,
          package_weight_gross: 3.9,
          package_size_width: 21,
          package_size_depth: 15,
          package_size_height: 26,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory9',
          factory: {
            id: 'factory9',
            name: 'Fábrica 9',
            url: 'https://fabrica9.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 9',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '10',
          name: 'Producto 10',
          msrp: 60,
          price: 50,
          sku: 'SKU010',
          description: 'Descripción del Producto 10',
          status: 'AVAILABLE',
          media: ['imagen19.jpg', 'imagen20.jpg'],
          item_weight_net: 2.5,
          item_weight_gross: 3.0,
          item_size_width: 20,
          item_size_depth: 15,
          item_size_height: 25,
          package_weight_net: 3.5,
          package_weight_gross: 4.0,
          package_size_width: 22,
          package_size_depth: 16,
          package_size_height: 27,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory10',
          factory: {
            id: 'factory10',
            name: 'Fábrica 10',
            url: 'https://fabrica10.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 10',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '11',
          name: 'Producto 11',
          msrp: 61,
          price: 51,
          sku: 'SKU011',
          description: 'Descripción del Producto 11',
          status: 'AVAILABLE',
          media: ['imagen21.jpg', 'imagen22.jpg'],
          item_weight_net: 2.6,
          item_weight_gross: 3.1,
          item_size_width: 21,
          item_size_depth: 16,
          item_size_height: 26,
          package_weight_net: 3.6,
          package_weight_gross: 4.1,
          package_size_width: 23,
          package_size_depth: 17,
          package_size_height: 28,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory11',
          factory: {
            id: 'factory11',
            name: 'Fábrica 11',
            url: 'https://fabrica11.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 11',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        },
        {
          id: '12',
          name: 'Producto 12',
          msrp: 62,
          price: 52,
          sku: 'SKU012',
          description: 'Descripción del Producto 12',
          status: 'AVAILABLE',
          media: ['imagen23.jpg', 'imagen24.jpg'],
          item_weight_net: 2.7,
          item_weight_gross: 3.2,
          item_size_width: 22,
          item_size_depth: 17,
          item_size_height: 27,
          package_weight_net: 3.7,
          package_weight_gross: 4.2,
          package_size_width: 24,
          package_size_depth: 18,
          package_size_height: 29,
          items_per_package: 1,
          categories: {
            nextToken: null,
            __typename: 'ModelProductCategoriesConnection'
          },
          factory_id: 'factory12',
          factory: {
            id: 'factory12',
            name: 'Fábrica 12',
            url: 'https://fabrica12.com',
            createdAt: '2024-03-31T12:00:00Z',
            updatedAt: '2024-03-31T12:00:00Z',
            __typename: 'Factory'
          },
          type: 'Tipo 12',
          createdAt: '2024-03-31T12:00:00Z',
          updatedAt: '2024-03-31T12:00:00Z',
          __typename: 'Product'
        }
        


      ];
  


      
      